#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"progress_bar": "00_core.ipynb",
         "resize_file": "00_core.ipynb",
         "show_img": "00_core.ipynb",
         "LABELS": "01_dataprep.ipynb",
         "FILENAME_TRIM": "01_dataprep.ipynb",
         "__label_colormap": "01_dataprep.ipynb",
         "COLORMAP": "01_dataprep.ipynb",
         "createjson": "01_dataprep.ipynb",
         "annotate_json": "01_dataprep.ipynb",
         "create_json_from_CSV": "01_dataprep.ipynb",
         "crop2well": "01_dataprep.ipynb",
         "well_circle_mask": "01_dataprep.ipynb",
         "check_well_crop": "01_dataprep.ipynb",
         "pad": "01_dataprep.ipynb",
         "get_image_size": "01_dataprep.ipynb",
         "resize_crop2well_one": "01_dataprep.ipynb",
         "label_from_json": "01_dataprep.ipynb",
         "DEFAULT_LABEL_FILL": "01_dataprep.ipynb",
         "create_one_label": "01_dataprep.ipynb",
         "resize_dir": "01_dataprep.ipynb",
         "resize_json_file": "01_dataprep.ipynb",
         "resize_json_dir": "01_dataprep.ipynb",
         "shuffle_csv": "01_dataprep.ipynb",
         "split_filenames": "01_dataprep.ipynb",
         "__crop_image": "01_dataprep.ipynb",
         "crop_img_dir": "01_dataprep.ipynb",
         "move_files_to_dir": "01_dataprep.ipynb",
         "old_move_files_to_dir": "01_dataprep.ipynb",
         "create_labels_dir": "01_dataprep.ipynb",
         "show_histogram": "05_histogram_utils.ipynb",
         "plot_color_histogram": "05_histogram_utils.ipynb",
         "plot_well_histograms": "05_histogram_utils.ipynb"}

modules = ["core.py",
           "dataprep.py",
           "histogram_utils.py"]

git_url = "https://github.com/johnnewto/cellsegment/tree/master/"

def custom_doc_links(name): return None